package lockdiff

import "testing"

func TestCargoLockParser(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  map[string]string
	}{
		{
			name: "multiple packages",
			input: `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abcdef"

[[package]]
name = "tokio"
version = "1.36.0"
source = "registry+..."
dependencies = [
 "bytes",
]
`,
			want: map[string]string{
				"serde": "1.0.197",
				"tokio": "1.36.0",
			},
		},
		{
			name: "section after package terminates the entry",
			input: `[[package]]
name = "foo"
version = "0.1.0"

[metadata]
key = "value"

[[package]]
name = "bar"
version = "2.0.0"
`,
			want: map[string]string{
				"foo": "0.1.0",
				"bar": "2.0.0",
			},
		},
		{
			name: "package without version is skipped",
			input: `[[package]]
name = "incomplete"
`,
			want: map[string]string{},
		},
		{
			name:  "empty input",
			input: "",
			want:  map[string]string{},
		},
	}

	parser := cargoLockParser{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parser.Parse([]byte(tt.input))

			if err != nil {
				t.Fatalf("Parse error: %v", err)
			}

			if len(got) != len(tt.want) {
				t.Fatalf("got %d entries, want %d (got=%v)", len(got), len(tt.want), got)
			}

			for name, wantVersion := range tt.want {
				if gotVersion, ok := got[name]; !ok || gotVersion != wantVersion {
					t.Errorf("got[%q] = %q (ok=%v), want %q", name, gotVersion, ok, wantVersion)
				}
			}
		})
	}
}

func TestCargoLockParserRegistered(t *testing.T) {
	parser, ok := ParserFor("Cargo.lock")

	if !ok {
		t.Fatal("Cargo.lock parser not registered")
	}

	if parser.Ecosystem() != "rust" {
		t.Errorf("Ecosystem() = %q, want %q", parser.Ecosystem(), "rust")
	}
}
