package lockdiff

import (
	"testing"
)

func TestYarnParser(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    map[string]string
		wantErr bool
	}{
		{
			name: "yarn v1 single entry",
			input: `# THIS IS AN AUTOGENERATED FILE
# yarn lockfile v1


"react@^18.0.0":
  version "18.3.1"
  resolved "https://registry.yarnpkg.com/react/-/react-18.3.1.tgz"
  integrity sha512-abc
`,
			want: map[string]string{"react": "18.3.1"},
		},
		{
			name: "yarn v1 scoped package with multiple specs",
			input: `"@scope/name@^1.0.0", "@scope/name@^1.0.5":
  version "1.0.5"
  resolved "https://..."
`,
			want: map[string]string{"@scope/name": "1.0.5"},
		},
		{
			name: "yarn berry with __metadata",
			input: `__metadata:
  version: 8
  cacheKey: 10

"@types/node@npm:^20.0.0":
  version: 20.10.0
  resolution: "@types/node@npm:20.10.0"

"vite@npm:5.0.0":
  version: 5.0.0
  resolution: "vite@npm:5.0.0"
`,
			want: map[string]string{
				"@types/node": "20.10.0",
				"vite":        "5.0.0",
			},
		},
		{
			name: "berry comma-separated header keeps both names deduped",
			input: `"@rollup/rollup-linux-x64-gnu@npm:^4.0.0, @rollup/rollup-linux-x64-gnu@npm:4.60.3":
  version: 4.60.3
  resolution: "@rollup/rollup-linux-x64-gnu@npm:4.60.3"
`,
			want: map[string]string{"@rollup/rollup-linux-x64-gnu": "4.60.3"},
		},
		{
			name:  "empty input returns empty map",
			input: "",
			want:  map[string]string{},
		},
		{
			name: "entry without version line is skipped",
			input: `"orphan@^1.0.0":
  resolved "https://..."
`,
			want: map[string]string{},
		},
	}

	parser := yarnParser{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parser.Parse([]byte(tt.input))

			if (err != nil) != tt.wantErr {
				t.Fatalf("err = %v, wantErr = %v", err, tt.wantErr)
			}

			if len(got) != len(tt.want) {
				t.Fatalf("got %d entries, want %d (got=%v)", len(got), len(tt.want), got)
			}

			for name, wantVersion := range tt.want {
				if gotVersion, ok := got[name]; !ok || gotVersion != wantVersion {
					t.Errorf("got[%q] = %q (ok=%v), want %q", name, gotVersion, ok, wantVersion)
				}
			}
		})
	}
}

func TestYarnParserRegistered(t *testing.T) {
	parser, ok := ParserFor("yarn.lock")

	if !ok {
		t.Fatal("yarn.lock parser not registered")
	}

	if parser.Ecosystem() != "node" {
		t.Errorf("Ecosystem() = %q, want %q", parser.Ecosystem(), "node")
	}
}
